### ISSUE TITLE
bug(frontend/app): replaying individual step run does not update workflowRun.status

### ISSUE THREAD

**Issue by grutt** [hatchet-dev/hatchet#164]
Problem: We're invalidating the workflow run when replaying an individual step, but the refetched data `workflow-runs/$run/index.tsx:34`  does not properly represent the state (always succeeded in the case of a succeded run). Because of this, the refetchInterval is never set to 

I've temporarily hotfix in #159 by always setting the refetch interval to 1s, but this is not a good solution in the long run.

**Comment by abelanger5** [comment]
This was fixed in #159
