### ISSUE TITLE
Problem when using hatchet frontend self-hosted

### ISSUE THREAD

**Issue by LeDuySon** [hatchet-dev/hatchet#251]
I got a problem when trying to access Hatchet frontend UI. It said "Please contact your Hatchet instance administrator to verify your email. Refresh this page once your email has been verified.". Can you guys help me with this?
![image](https://github.com/hatchet-dev/hatchet/assets/33374938/374421c9-ec77-4082-81a8-35275ea464f2)

**Comment by steebchen** [comment]
Which deployment are you using (Kubernetes or Docker Compose)?

If you have an env file set up, you can try adding `SERVER_AUTH_SET_EMAIL_VERIFIED=true` and restarting. I think we'll have to adapt and/or clarify in the quickstart.

**Comment by giubaru** [comment]
Hey, I was having the same problem using it in a EC2 AWS server, try checking you Caddyfile, maybe you need to change the `http://localhost:8080` to `http://your-domain:8080` (or maybe 0.0.0.0 but I didn't try it)

```
http://testing.my-domain:8080 {
	handle /api/* {
		reverse_proxy hatchet-api:8080
	}
	handle /* {
		reverse_proxy hatchet-frontend:80
	}
}
```

**Comment by LeDuySon** [comment]
Hi @giubaru , thank you! I have fixed that by changing to http://:8080. It works with all interface

**Comment by grutt** [comment]
Thank you @LeDuySon , @giubaru did that resolve your issue?

**Comment by giubaru** [comment]
@grutt Yes, the proposed by @LeDuySon worked better for me as well.

**Comment by grutt** [comment]
Just pushed fixes for this in both the python and typescript quickstarts. Thanks @LeDuySon for helping out on this.
