### ISSUE TITLE
docs: typescript streaming

### ISSUE THREAD

**Issue by grutt** [hatchet-dev/hatchet#254]
Event streaming for workflow runs is now available in the Typescript SDK version 0.1.27

Example of how to listen for events with a workflow run id here:
https://github.com/hatchet-dev/hatchet-typescript-quickstart/blob/main/simple-examples/example-event-with-results.ts

This affects the following pages:
- [ ] https://docs.hatchet.run/home/features/streaming

**Comment by SwarajBaral** [comment]
Hey I would like to pick this up. Just to clarify, the example that you have linked needs to be added to the streaming section of the docs, right ?

**Comment by grutt** [comment]
Thanks @SwarajBaral appreciate that. It would be great to see the linked typescript example, and relevant snippets from the python tutorial at the bottom section of the docs on the page.

Having a short explanation for both would be fantastic too.

You can see how we generally tab languages on other doc pages.

**Comment by SwarajBaral** [comment]
Thank you @grutt

**Comment by grutt** [comment]
@SwarajBaral are you still planning on picking this up?

**Comment by SwarajBaral** [comment]
Hey sorry, yeah i had picked it up. Didn't get a chance to raise the MR, got caught up in stuff. Looks like its done tho. So I will pick something else up. Sorry again.
