### ISSUE TITLE
[question] Is there an option to pause/resume workflows?

### ISSUE THREAD

**Issue by tadeoos** [hatchet-dev/hatchet#276]
Hey,

I'm very excited about this project and have a glimmer of hope this could help cure my Celery PTSD ;)
While reading the documentation (not yet finished, so forgive me if this is somewhere down the road, but my sense is that it may be not) I started pondering if hatchet's Workflow abstraction could handle a use case where a workflow needs to be halted (for example there is a "manual QA" needed from a real person). Ideally there would be a way to dynamically add something to the context during this QA and resume the workflow.
Is this something you ever considered? Perhaps you have an idea how one could go about trying to implement this with the current version? Is this even feasible at the moment?

All the best, I'm rooting for you folks :)

**Comment by tadeoos** [comment]
Damn, I think I spoke too fast, just got to the "Manual Intervention for Workflow Continuation" section of https://docs.hatchet.run/home/features/durable-execution
I think this answers most of my questions... But I guess this will mean I would need to put the workflow in a failed state first, correct?

**Comment by grutt** [comment]
Hi @tadeoos, you can replay any step at any time and modify the context. No need to fail the workflow first.
