### ISSUE TITLE
docs (typescript sdk): namespace config variable

### ISSUE THREAD

**Issue by grutt** [hatchet-dev/hatchet#278]
just published typescript 0.1.29 to add an optional namespace to the hatchet config:
```
const hatchet = Hatchet.init({
  namespace: 'dev',
});
```
or by setting the `HATCHET_CLIENT_NAMESPACE` env variable.

the docs at https://docs.hatchet.run/home/basics/environments should be updated to describe this option (for typescript for now)

it is still recommended to run a production tenant that is separate from dev/local. this should be clearly described in the docs.

**Comment by aeswibon** [comment]
Would like to work on this issue.
