### ISSUE TITLE
feat(python sdk): namespace config var

### ISSUE THREAD

**Issue by grutt** [hatchet-dev/hatchet#279]
[typescript/#27](https://github.com/hatchet-dev/hatchet-typescript/pull/27) added a namespace configuration prop to improve the local developer experience for multiple devs on a single hatchet tenant.

We need the same namespacing functionality for the Python SDK 

Related #278

**Comment by aeswibon** [comment]
Would like to work on this issue.

**Comment by grutt** [comment]
thanks @aeswibon, please reference this issue in your PR

**Comment by aeswibon** [comment]
Sure 😊😊

**Comment by abelanger5** [comment]
fixed by #354
