### ISSUE TITLE
feat: Add Docker Swarm configuration

### ISSUE THREAD

**Issue by pveierland** [hatchet-dev/hatchet#298]
Hello,

The Docker Compose configuration provided in the documentation is not suitable for use with Docker Swarm due to its use of depends_on for startup sequencing, which is ignored in swarm mode. It would be great if a robust Docker Swarm configuration was provided that did not depend on this feature.

https://docs.hatchet.run/self-hosting/docker-compose
https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on

**Comment by pveierland** [comment]
Leaving a note here as we had issues running the Hatchet images on macOS / ARM with docker swarm. The following solved the issue for us:

```
docker stack deploy --resolve-image "never" -c stack.yml stack
```

https://stackoverflow.com/questions/72018377/is-there-a-way-to-deploy-x86-images-on-a-apple-silicon-arm-using-docker-stack/74654737#74654737

**Comment by sanzoghenzo** [comment]
Hi @pveierland 

Did you come up with a good solution for this?

I'm looking at it right now, it would be wonderful if you can share your progress on this!

**Comment by pveierland** [comment]
We've moved to k8s now for our deployment of hatchet based on the official helm chart.
