### ISSUE TITLE
light theme

### ISSUE THREAD

**Issue by yuuuxt** [hatchet-dev/hatchet#345]
For web UI and documentation, could you add a switch to use light theme? Thanks!

**Comment by AlexBarabash** [comment]
I agree, that would be great! I have astigmatism and it makes it really hard to read the light-on-dark text. It's a pretty common medical condition too, so there are probably a lot more people with this issue than you might think. And I personally would really appreciate having an option to switch to a light theme.

**Comment by grutt** [comment]
adding light mode to dashboard first, docs has a bit of complexity in configuration but plan on addressing it soon!

**Comment by steebchen** [comment]
@grutt created this PR https://github.com/hatchet-dev/hatchet/pull/386 for the docs as I've already seen how it was attached. note I removed the `primaryHue` attribute which made the links (and maybe other stuff) less bright in dark mode.

**Comment by steebchen** [comment]
@abelanger5 was there any reasoning to only use the dark theme? I guess it's easy for the docs; for the UI it would need some continuous maintenance to make sure everything is readable with both light and dark modes

**Comment by grutt** [comment]
@steebchen any reason this was reopened?

**Comment by steebchen** [comment]
The PR I merged is just for the docs repo, not the main app/UI

**Comment by grutt** [comment]
Yep, I handled the App in #381 
Should be good on this for now :)

**Comment by yuuuxt** [comment]
Thanks for the update!
