### ISSUE TITLE
Contributing: do not require messing with hosts file

### ISSUE THREAD

**Issue by steebchen** [hatchet-dev/hatchet#4]
```
127.0.0.1 app.dev.hatchet-tools.com
```

We can just set this as an actual DNS entry I think

**Comment by abelanger5** [comment]
Sure, done:

```
nslookup app.dev.hatchet-tools.com
Non-authoritative answer:
Name:   app.dev.hatchet-tools.com
Address: 127.0.0.1
```

Took a quick look at any security issues this may cause, only one that seemed relevant is [same-site scripting](https://web.archive.org/web/20190922205241/https://www.securityfocus.com/archive/1/486606/30/0/threaded) but this seems like it involves domain spoofing and only seems relevant if someone is able to run a webserver on your network.
