### ISSUE TITLE
[feature request] typescript when has Scheduling Workflows and Child Workflows

### ISSUE THREAD

**Issue by maobase** [hatchet-dev/hatchet#430]
see the docs https://docs.hatchet.run/sdks/go-sdk/child-workflows, i am not found Scheduling Workflows and Child Workflows in typescript sdk

**Comment by abelanger5** [comment]
Hey @maobase, this is available in the Typescript SDK. There are Typescript examples here: https://docs.hatchet.run/home/features/child-workflows. 

We're working on the docs, thanks for flagging that this is confusing.
