### ISSUE TITLE
feat: support linux/arm64/v8 platform

### ISSUE THREAD

**Issue by jinrenjie** [hatchet-dev/hatchet#480]
The following images do not support linux/arm64/v8 yet

* hatchet-migrate:latest
* hatchet-admin:latest
* hatchet-engine:latest
* hatchet-api:latest

Hope it can be adapted to linux/arm64/v8, thanks!

**Comment by abelanger5** [comment]
Hey @jinrenjie, `linux/arm64` support is now available in release `v0.32.0` and above!
