### ISSUE TITLE
Find a workflow run by original input field

### ISSUE THREAD

**Issue by clintwood** [hatchet-dev/hatchet#528]
Using the typescript client node.js module, is there a way to find an existing event by filtering on a field passed in the event data e.g.: `client.event.push('event-name', { myId: 'some-id' });` - find the event where `myId` is `some-id`?

**Comment by abelanger5** [comment]
I believe I just responded on Discord but copying here for visibility + tracking:

This would be something that you can use additional metadata for: https://docs.hatchet.run/home/features/additional-metadata. 

I'm not sure if our Typescript API is exposing our list events method -- will need to double-check that -- but if it does, you can filter by the metadata field, which should only return a single result.

**Comment by clintwood** [comment]
Thank you - yes!
