### ISSUE TITLE
docs: Kubernetes Quickstart examples are incomplete

### ISSUE THREAD

**Issue by kosmoz** [hatchet-dev/hatchet#539]
The example workers found at https://docs.hatchet.run/self-hosting/kubernetes#run-your-first-worker do not work without major changes. It would be really useful for users to know which configuration properties they have to set in order to get it working. 

In my case, the following config worked (typescript example):
```json
{
  "token": "xxxxx",
  "api_url": "http://localhost:7000/",
  "tenant_id": "xxxxx",
  "host_port": "7000",
  "tls_config": {
    "tls_strategy": "none"
  }
}
```

Also, I'm not quite sure what the `dotenv` dependency adds to the example, since it doesn't seem to do anything.

**Comment by abelanger5** [comment]
I've closed this - this config shouldn't be necessary in the Typescript SDK and I wasn't able to reproduce. One thing that was unclear in the original docs was that the `HATCHET_CLIENT_TLS_STRATEGY=none` variable should be written to a `.env` file, which we've clarified. There should only be two env vars necessary -- `HATCHET_CLIENT_TOKEN` and `HATCHET_CLIENT_TLS_STRATEGY`. It sounds like these weren't written to a `dotenv` file in your case. 

Happy to reopen if you're still having difficulty 👍
