### ISSUE TITLE
feat: add streaming endpoint which returns events according to metadata value

### ISSUE THREAD

**Issue by abelanger5** [hatchet-dev/hatchet#593]
User request: support use-cases where the workflow run ids aren't known (for example, in a separate long-lived streaming endpoint). In this case we'd like to get all stream events corresponding to a metadata tag.

**Comment by clintwood** [comment]
It would be good to be able to use the same [parameters](https://github.com/hatchet-dev/hatchet-typescript/blob/87bbe33a52bfeda7fa9c405901f9ecbc5c1e3922/src/clients/rest/generated/Api.ts#L1316) used to get a list of workflow runs for this feature
