### ISSUE TITLE
hatchet-lite doesnt seem to be setting up properly.

### ISSUE THREAD

**Issue by mattrochon** [hatchet-dev/hatchet#611]
Followed the instructions which consisted of copy/pasting the docker compose file and running:

docker compose -f ./docker-compose.hatchet.yaml up

everything looks like it starts up but I am unable to log in.

An inspection of the logs shows:

![image](https://github.com/hatchet-dev/hatchet/assets/1702787/64f02251-2799-4f96-a63a-232eb862149d)

When there should obviously be migrations.

**Comment by abelanger5** [comment]
Hey @mattrochon, taking a look at this. There's a chance the migration ran on a previous startup of the container, are there any logs further up when you click into the `hatchet-lite-hatchet-lite-1` container on docker desktop (or via `docker logs...`)?

> everything looks like it starts up but I am unable to log in.

What do you see when you try to log in? There should be an associated error log here as well.

**Comment by mattrochon** [comment]
![image](https://github.com/hatchet-dev/hatchet/assets/1702787/3686eda8-69b9-4cc3-a894-c170f869d3d4)

There are a significant amount of logs.
1. Postgres startup, seems to be ok, though I did have to add PGUSER to the env in the yaml file
2. Rabbit MQ startup - it seems to error our tryign to connect to rmq first, then decides its not runnign and starts it up
3. After rmq starts then it checks the db. THe prisma migrations table doesnt exist yet, so no migrations would have been run, assuming that the atlas migrations still updates the prisma table.

![image](https://github.com/hatchet-dev/hatchet/assets/1702787/62b30ad6-6ca1-4fb2-88f4-e8184a429743)

the atlas-apply script seems to suggest that it does.

**Comment by abelanger5** [comment]
Thanks for the additional info. A couple other questions:

1. Seeing `Please provide valid credentials` is expected, since we check `GET /api/v1/users/current` when you load `localhost:8080`. What are the logs when you try to log in with:

    ```
    Email: admin@example.com
    Password: Admin123!!
    ```

2. To address this:

    > THe prisma migrations table doesnt exist yet, so no migrations would have been run, assuming that the atlas migrations still updates the prisma table.

    The atlas migrations don't update the prisma table - this case should only be hit if you're upgrading from an older version of Hatchet (pre-`0.31.0`). 

    One way we can check if the migrations ran is by adding:

    ```yaml
    services:
      postgres:
        # ... rest of config
        ports:
          - "5432:5432"
    # ... rest of config
    ```

    And then running `psql 'postgresql://hatchet:hatchet@localhost:5432/hatchet'`, and inside of the shell, run `\dt` and let me know what it outputs?

**Comment by mattrochon** [comment]
You're right, looks like the db was created.

![image](https://github.com/hatchet-dev/hatchet/assets/1702787/0bfe04ea-4774-4207-8b91-b5266dd91708)

THe error message is the exact same when i try to log in. No error appears on the page, only in the logs.

The default user also appears to exist.

![image](https://github.com/hatchet-dev/hatchet/assets/1702787/558600ec-1522-4538-b8a0-d8fbaa0532c1)

**Comment by mattrochon** [comment]
OK i think the issue is i'm not running it on localhost. I have it running in a remote docker host on my local network.

![image](https://github.com/hatchet-dev/hatchet/assets/1702787/7783208c-761f-4cf7-8164-4eff0f11f8c9)

**Comment by abelanger5** [comment]
Ah, yeah the cookie has a domain attribute set to `localhost`. You can change the value of `SERVER_AUTH_COOKIE_DOMAIN` in the configuration and see if that helps?

**Comment by mattrochon** [comment]
Confirmed works, was user-error all along, thanks for the help!
