### ISSUE TITLE
bug(frontend) - Changing password on hatchet lite not possible (infinite loops)

### ISSUE THREAD

**Issue by semse** [hatchet-dev/hatchet#716]
Going into settings -> members leads to some kind of infinite loop leading the UI to make repeated requests to /api/v1/meta every 200ms. This leads to the UI refreshing and makes it impossible to change your password.

Tested in Chrome, Brave, and Arc browser.

<img width="1061" alt="Screenshot 2024-07-12 at 10 03 02" src="https://github.com/user-attachments/assets/ffb8bf69-db3f-4735-b478-4fe2a2f0c778">

**Comment by abelanger5** [comment]
Hey @semse, thanks for the report! Taking a look at this and should have a fix up by end of day.
