### ISSUE TITLE
refactor: reduce usage of `json.Marshal` and consider alternatives

### ISSUE THREAD

**Issue by abelanger5** [hatchet-dev/hatchet#88]
We marshal to/from a bunch of types during the lifecycle of a step run. We should cache the raw JSON bytes and converted objects, wherever possible, and consider an alternative like [`go-json`](https://github.com/goccy/go-json) to speed up decoding.

**Comment by khareyash05** [comment]
Hey @abelanger5 if this is open can i take this one up?
