### ISSUE TITLE
Dynamic Rate Limits with RateLimitDuration.SECOND not working

### ISSUE THREAD

**Issue by ndriJK** [hatchet-dev/hatchet#948]
Hi,
I defined a dynamic rate limit for a step

```
{
          dynamicKey: "input.org_id",
          units: 1,
          limit: 10,
          duration: RateLimitDuration.SECOND
        }
```

But in the dashboard the rate limit duration is per minute instead of per second. Is it a bug or don't you support seconds ?

**Comment by grutt** [comment]
Hi @ndriJK this was fixed in #936 and published but is not yet tagged as latest. You should be able to specify docker image version `0.48.2` to pull these changes.

**Comment by ndriJK** [comment]
Thanks @grutt actually we are hosted on hatchet.run

**Comment by grutt** [comment]
@ndriJK Gotcha, we'll have this release pushed up to cloud shortly.
